type DegreeNameItem = {
  id: number;
  name: string;
};

type education_boards = {
  id: number;
  name: string;
};

type EducationItem = {
  id: number;
  name: string;
  degree_name?: DegreeNameItem[];
  education_board?: education_boards[];
};

export const education_data: EducationItem[] = [
  {
    id: 1,
    name: "Secondary",
    degree_name: [
      { id: 1, name: "SSC" },
      { id: 2, name: "O Level" },
      { id: 3, name: "Dakhil (Madrasah)" },
      { id: 4, name: "SSC (Vocational)" },
      { id: 5, name: "Other" },
    ],
    education_board: [
      { id: 6, name: "Barishal" },
      { id: 5, name: "Chattogram" },
      { id: 3, name: "Cumilla" },
      { id: 1, name: "Dhaka" },
      { id: 10, name: "Dinajpur" },
      { id: 4, name: "Jashore" },
      { id: 11, name: "Mymensingh" },
      { id: 2, name: "Rajshahi" },
      { id: 7, name: "Sylhet" },
      { id: 8, name: "Madrasah" },
      { id: 9, name: "Technical" },
      { id: 12, name: "BOU" },
    ],
  },
  {
    id: 2,
    name: "Higher Secondary",
    degree_name: [
      { id: 1, name: "HSC" },
      { id: 2, name: "A Level" },
      { id: 3, name: "Alim (Madrasah)" },
      { id: 4, name: "HSC (Vocational)" },
      { id: 5, name: "HSC (BMT)" },
      { id: 6, name: "Other" },
    ],
  },
  {
    id: 3,
    name: "Diploma",
    degree_name: [
      { id: 1, name: "Certificate in Marine Trade" },
      { id: 2, name: "Diploma (Vocational)" },
      { id: 3, name: "Diploma in Agriculture" },
      { id: 4, name: "Diploma in Anesthesiology (DA)" },
      { id: 5, name: "Diploma in Architecture" },
      { id: 6, name: "Diploma in Automobile" },
      { id: 7, name: "Diploma in Biomedical Engineering (BME)" },
      { id: 8, name: "Diploma in Business Studies" },
      { id: 9, name: "Diploma in Cardiology (D.Card)" },
      { id: 10, name: "Diploma in Civil" },
      { id: 11, name: "Diploma in Commerce" },
      { id: 12, name: "Diploma in Computer" },
      { id: 13, name: "Diploma in Culinary Art" },
      { id: 14, name: "Diploma in Electrical" },
      { id: 15, name: "Diploma in Electro Medical Engineering (EME)" },
      { id: 16, name: "Diploma in Electro medical" },
      { id: 17, name: "Diploma in Electronics" },
      { id: 18, name: "Diploma in Engineering" },
      { id: 19, name: "Diploma in Fisheries" },
      { id: 20, name: "Diploma in Forestry" },
      { id: 21, name: "Diploma in Glass & Ceramic Technology" },
      { id: 22, name: "Diploma in Gynecology and Obstetrics (DGO)" },
      { id: 23, name: "Diploma in Health Technology and Services" },
      { id: 24, name: "Diploma in Hotel Management" },
      { id: 25, name: "Diploma in Laryngology and Otology (DLO)" },
      { id: 26, name: "Diploma in Livestock" },
      { id: 27, name: "Diploma in Marine Engineering" },
      { id: 28, name: "Diploma in Mechanical" },
      { id: 29, name: "Diploma in Medical" },
      { id: 30, name: "Diploma in Medical Technology" },
      { id: 31, name: "Diploma in Medical Technology (Physiotherapy)" },
      { id: 32, name: "Diploma in Medical Ultrasound" },
      { id: 33, name: "Diploma in Midwifery" },
      { id: 34, name: "Diploma in Nursing" },
      { id: 35, name: "Diploma in Orthopaedics (D.Ortho)" },
      { id: 36, name: "Diploma in Pathology" },
      { id: 37, name: "Diploma in Power" },
      { id: 38, name: "Diploma in Refrigeration and Air Conditioning" },
      { id: 39, name: "Diploma in Textile Engineering" },
      {
        id: 40,
        name: "Membership of the Royal College of Obstetricians and Gynaecologists (MRCOG)",
      },
      {
        id: 41,
        name: "Membership of the Royal Colleges of Physicians (MRCP)",
      },
      {
        id: 42,
        name: "Membership of the Royal Colleges of Surgeons (MRCS)",
      },
      { id: 43, name: "Others" },
      { id: 44, name: "Post Graduate Diploma (PGD)" },
    ],
  },
  {
    id: 4,
    name: "Bachelor/Honors",
    degree_name: [
      { id: 1, name: "Bachelor in Engineering (BEngg)" },
      { id: 2, name: "Bachelor of Architecture (B.Arch)" },
      { id: 3, name: "Bachelor of Arts (BA)" },
      { id: 4, name: "Bachelor of Arts (Pass)" },
      { id: 5, name: "Bachelor of Business Administration (BBA)" },
      { id: 6, name: "Bachelor of Business Studies (BBS)" },
      { id: 7, name: "Bachelor of Business Studies (Pass)" },
      { id: 8, name: "Bachelor of Commerce (BCom)" },
      { id: 9, name: "Bachelor of Commerce (Pass)" },
      { id: 10, name: "Bachelor of Computer Application (BCA)" },
      { id: 11, name: "Bachelor of Dental Surgery (BDS)" },
      { id: 12, name: "Bachelor of Education (B.Ed)" },
      { id: 13, name: "Bachelor of Fine Arts (B.F.A)" },
      { id: 14, name: "Bachelor of Law (LLB)" },
      { id: 15, name: "Bachelor of Law (Pass)" },
      {
        id: 16,
        name: "Bachelor of Medicine and Bachelor of Surgery (MBBS)",
      },
      { id: 17, name: "Bachelor of Pharmacy (B.Pharm)" },
      { id: 18, name: "Bachelor of Physical Education (BPEd)" },
      { id: 19, name: "Bachelor of Physiotherapy (BPT)" },
      { id: 20, name: "Bachelor of Public Health" },
      { id: 21, name: "Bachelor of Real Estate (BRE)" },
      { id: 22, name: "Bachelor of Science (BSc)" },
      { id: 23, name: "Bachelor of Science (Pass)" },
      { id: 24, name: "Bachelor of Social Science (BSS)" },
      { id: 25, name: "Bachelor of Social Science (Pass)" },
      { id: 26, name: "Doctor of Veterinary Medicine (DVM)" },
      { id: 27, name: "Fazil (Madrasah Hons.)" },
      { id: 28, name: "Fazil (Madrasah Pass)" },
      { id: 29, name: "Others" },
    ],
  },
  {
    id: 5,
    name: "Postgraduate",
    degree_name: [
      { id: 1, name: "Doctor of Medicine (MD)" },
      { id: 2, name: "Executive Master of Business Administration (EMBA)" },
      {
        id: 3,
        name: "Fellowship of the College of Physicians and Surgeons (FCPS)",
      },
      { id: 4, name: "Kamil (Madrasah)" },
      { id: 5, name: "Master of Architecture (M.Arch)" },
      { id: 6, name: "Master of Arts (MA)" },
      { id: 7, name: "Master of Business Administration (MBA)" },
      { id: 8, name: "Master of Business Management (MBM)" },
      { id: 9, name: "Master of Business Studies (MBS)" },
      { id: 10, name: "Master of Commerce (MCom)" },
      { id: 11, name: "Master of Development Studies (MDS)" },
      {
        id: 12,
        name: "Master of Disability Management and Rehabilitation (MDMR)",
      },
      { id: 13, name: "Master of Education (M.Ed)" },
      { id: 14, name: "Master of Fine Arts (M.F.A)" },
      {
        id: 15,
        name: "Master of Information & Communication Technology (MICT)",
      },
      { id: 16, name: "Master of Law (LLM)" },
      { id: 17, name: "Master of Pharmacy (M.Pharm)" },
      { id: 18, name: "Master of Philosophy (M.Phil)" },
      { id: 19, name: "Master of Physiotherapy (MPT)" },
      { id: 20, name: "Master of Professional Banking (MPB)" },
      { id: 21, name: "Master of Professional Finance (MPF)" },
      { id: 22, name: "Master of Professional Marketing (MPM)" },
      { id: 23, name: "Master of Professional MIS (MPMIS)" },
      { id: 24, name: "Master of Science (MSc)" },
      { id: 25, name: "Master of Social Science (MSS)" },
      { id: 26, name: "Master of Surgery (MS)" },
      { id: 27, name: "Masters in Bank Management (MBM)" },
      { id: 28, name: "Masters in Computer Application (MCA)" },
      { id: 29, name: "Masters in Engineering (MEngg)" },
      { id: 30, name: "Masters in Information Systems Security (MISS)" },
      {
        id: 31,
        name: "Masters of Professional Human Resource Management (MPHRM)",
      },
      { id: 32, name: "Others" },
    ],
  },
  {
    id: 6,
    name: "PhD",
  },
];
